---
title: "MSD Homework 2, Problem 3"
author: "Mane Diouf & Mary McTarsney"
date: '`r Sys.time()`'
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(here)
library(scales)
library(tidyverse)
library(cfbfastR)

theme_set(theme_bw())

knitr::opts_chunk$set(echo = TRUE)
```

# Define the footbal game schedules

```{r}
sched <- map_dfr(2000:2005, espn_cfb_schedule)

```

# Save the schedule file

```{r}
write_csv(sched, file = "game_schedule.csv")
```

# -- Team to agency mapping --

## Load the batch header file
```{r}
batch_header <- read_csv("nibrs_batch_header_1991_2024.csv")
```

```{r}
# Create a dataset that contains the needed 26 schools towns with their
# corresponding state abbreviations, school names, and short team labels

paper_cities <- tibble(
    city_name=c("akron", "ames", "ann arbor","athens","austin","Blacksburg","boise","clemson","Colorado Springs",
    "Columbia","Columbus","Denton","East Lansing","Fayetteville","Huntington","Iowa City","Jonesboro",
    "Kalamazoo","Lawrence","Logan","Lubbock","Morgantown","Moscow","Mount Pleasant","Murfreesboro","Provo"),
    state_abbreviation=c("oh", "ia","mi","oh","tx","va","id","sc","co","sc","oh","tx","mi","ar","wv","ia","ar","mi",
    "ks","ut","tx","wv","id","mi","tn","ut"),
    school=c("the university of akron", "iowa state university","the university of michigan","ohio university",
        "the University of Texas at Austin","Virginia Polytechnic Institute and State University","Boise State University",
        "Clemson University","United States Air Force Academy","The University of South Carolina","The Ohio State University",
        "The University of North Texas","Michigan State University","University of Arkansas","Marshall University",
        "The University of Iowa","Arkansas State University","Western Michigan University","The University of Kansas",
        "Utah State University","Texas Tech University","West Virginia University","The University of Idaho",
        "Eastern Michigan University","Middle Tennessee State University","Brigham Young University")
) %>%
    mutate(across(everything(), ~ str_to_lower(as.character(.)))) %>%
    mutate(team=c("Akron","Iowa State","Michigan","Ohio","Texas","Virginia Tech","Boise State","Clemson",
        "Air Force","South Carolina","Ohio State","North Texas","Michigan State","Arkansas","Marshall","Iowa",
        "Arkansas State","Western Michigan","Kansas","Utah State","Texas Tech","West Virginia","Idaho",
        "Eastern Michigan","Middle Tennessee","BYU")) 
```

## Overall records with ori, city, state, and agency agency indicator

```{r}
header <- batch_header %>%
    filter(year == 2000) %>%
    select(c("ori","city_name","state_abbreviation","agency_indicator")) %>%
    unique()
```
```{r}
ori_mapping <- left_join(
    paper_cities, 
    header, 
    by=c("city_name","state_abbreviation")
    ) %>% 
    filter(agency_indicator == "city")

write_csv(ori_mapping, "ori_mapping.csv")
``` 

# Reproduction of table 2 (Distribution of games by day of week)

```{r}
# Initiate the team names with their matching universities
# so that we can easily match if the teams are either
# home teams or away teams  

university_team_lookup <- tribble(
  ~university, ~team_name,
  'the university of akron', 'Zips',
  'iowa state university', 'Cyclones',
  'the university of michigan', 'Wolverines',
  'ohio university', 'Bobcats',
  'the university of texas at austin', 'Longhorns',
  'virginia polytechnic institute and state university', 'Hokies',
  'boise state university', 'Broncos',
  'clemson university', 'Tigers',
  'united states air force academy', 'Falcons',
  'the university of south carolina', 'Gamecocks',
  'the ohio state university', 'Buckeyes',
  'the university of north texas', 'Mean Green',
  'michigan state university', 'Spartans',
  'university of arkansas', 'Razorbacks',
  'marshall university', 'Thundering Herd',
  'the university of iowa', 'Hawkeyes',
  'arkansas state university', 'Red Wolves',
  'western michigan university', 'Broncos2',
  'the university of kansas', 'Jayhawks',
  'utah state university', 'Aggies',
  'texas tech university', 'Red Raiders',
  'west virginia university', 'Mountaineers',
  'the university of idaho', 'Vandals',
  'eastern michigan university', 'Eagles',
  'middle tennessee state university', 'Blue Raiders',
  'brigham young university', 'Cougars'
)

# Recreate table 2 that creates a weekday summary of games and offenses 
# Based on the initial schedule file,
# we filter out the home or away team that played daily

game_week <- sched %>%
    mutate(day_of_the_week=lubridate::wday(game_date, label = TRUE, abbr = FALSE))%>% 
    filter(home_team_name %in% university_team_lookup$team_name | away_team_name %in% university_team_lookup$team_name) %>% 
    group_by(day_of_the_week) %>% 
    summarize(
        num_games=n()
    )

# Add an additional row for "Total" to the existing table 
game_week <- bind_rows(
  game_week,
  tibble(day_of_the_week = "Total", num_games = sum(game_week$num_games))
)
```